apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  REACT_APP_YOUR_HOSTNAME: aHR0cDovL2xvY2FsaG9zdDozMDAwNQo=
  ATLAS_URI: bW9uZ29kZGI6Ly9tb25nb2RiLXNlcnZpY2U6MjcwMTcvcmVjb3Jkcwo=
